### PR TITLE
Topic/vel ref gen cleaning restructuring

### PR DESCRIPTION
**Pull request by andrei-herdt**
Some clean up and a bugfix

### CODE REVIEW

**Comment by olivier-stasse** [comment]
Dear Andrei,
Thanks for your pull request.
However because you did not follow the indention requirements, and did not update your branch against the master regulary, the verification of those commits will take time.
By the way, the git interface is wrong regarding the changes, it compares only the reference between your commits and not with the master.
A cherry-pick of your commit ac2d102 is messing up the merge of git.

**Comment by andrei-herdt** [comment]
OK, so then I will try to make the merge here and I make another pull request?

**Comment by olivier-stasse** [comment]
Hi Andrei,
Thanks for your help. It took a bit of time for merging.
Few comments:
1/ Please remove trailing whitespace. But this hold although for the other contributors, I
found a lot in the master.
2/ Do not put types in PGTypes.h unless they are needed in the API. I added a privatepgtypes.h to allow internal wide namespace for types.
This is important because it gives the algorithm designers the possibility to change the internal structure of the algorithm without impacting the user.

Everything is now waiting in topic/merge-vel-ref.
I want to write a regression test for your algorithm and check with you if the outputs are the them.
Once this is validated I will push in the master.

Thanks again for your contribution.

Olivier.

**Comment by olivier-stasse** [comment]
Hi Andrei, 
I finished the regression test and the merge is waiting in topic/merge-vel-ref.

The code is working with the sample robot now. The problem was coming from
the size of the constraints related to the feet. I removed
the hard-coded values.

I noticed several points to fix to clean up the code:
1/ Please uses the prefix m_ for members of the objects and 
the prefix l for local variables.
As you mixed the two notations, it did not help to read the code.

2/ We should cut the code in smaller pieces and add more comments.
(Well that's easy to say but I know how difficult it is for a numerical algorithm,
and moreover the same remark apply to my code).
I did try to help by removing some synchronization mechanisms for the constraints
on the feet in an external structure.

3/ If you do not validate the code by the end of the week, I will consider it as a tacit aggreement and merge it into the master for a validation on HRP-2.

4/ Could you try to update your changes from the master once this is merged.

5/ Note that we will soon use submodules for cmake and try to reinforce 
the coding style.

6/ I apologize for the commits in your branch I reverted all my modifications.

Thanks again for you contribution.
Best,
Olivier.

**Comment by andrei-herdt** [comment]
OK, I will try to improve the first two points that you mentioned the next few days and hopefully some other minor things.

Best,

Andrei

**Comment by olivier-stasse** [comment]
Commit 1027e3296c07b8608674 realizing this merge has been tested on the robot.
This pull request is therefore closed.

**Pull request merged**
